/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * @file    main.c
 * @brief   模拟闭环控制系统 - 题目3
 *
 * 功能:
 *   1. DAC输出模拟电压 (PA4)，通过按键设置目标电压
 *   2. ADC采集DAC输出 (PA0)，闭环反馈
 *   3. ADC窗口检测：电压过高/过低 -> LED闪烁 + 蜂鸣器 + 串口报警
 *   4. 串口主机可设置目标电压和窗口阈值
 *   5. STM32F407 内部温度传感器 (ADC1_IN16) 采集片内温度
 *   6. TFT LCD (FSMC) 显示目标/实测电压、窗口阈值、片内温度、报警状态
 *
 * 引脚分配:
 *   PA5  - ADC2_IN5 (闭环反馈, 连接DAC via wire)
 *   PA4  - DAC_OUT1 (模拟输出)
 *   PA9  - USART1_TX
 *   PA10 - USART1_RX
 *   PD12 - LED4 (Green)  - 正常指示
 *   PD13 - LED3 (Orange) - 报警指示
 *   PD14 - LED5 (Red)    - 报警闪烁
 *   PD15 - LED6 (Blue)   - 状态指示
 *   PC0  - KEY_UP  (电压+0.1V)
 *   PC1  - KEY_DOWN (电压-0.1V)
 *   PF8  - Buzzer  (蜂鸣器, active-high)
 *   LCD  - FSMC Bank1 NE4: PD/PE/PF12(A6)/PG12(NE4), PB15背光
 *
 * 注意: ALIENTEK Explorer F407 板上 silk-screen 标 "ADC/TPAD" 的是 PA5;
 *       silk-screen 标 "PA0/WKUP" 的才是真正的 PA0, 两者不在同一焊盘.
 */

#include "system.h"
#include "uart.h"
#include "dac.h"
#include "adc.h"
#include "lcd.h"
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

/*---------- 引脚定义 ----------*/
#define LED_GREEN       (1U << 12)
#define LED_ORANGE      (1U << 13)
#define LED_RED         (1U << 14)
#define LED_BLUE        (1U << 15)
#define LED_ALL         (LED_GREEN | LED_ORANGE | LED_RED | LED_BLUE)

/* BUZZER (PF8) — ALIENTEK 探索者 STM32F407
 * 例程配置: GPIO_PuPd_DOWN + 默认 GPIO_ResetBits (拉低 = 静音),
 * 也就是说 PF8=1 时蜂鸣器响 (active-high). */
#define BUZZER_PIN      (1U << 8)    /* PF8 (BEEP) */
#define KEY0_PIN        (1U << 4)    /* PE4 (KEY0) */
#define KEY1_PIN        (1U << 3)    /* PE3 (KEY1) */
#define KEY2_PIN        (1U << 2)    /* PE2 (KEY2) */

/*---------- 全局状态 ----------*/
static float target_voltage = 1.5f;
static float measured_voltage = 0.0f;
static float chip_temperature = 0.0f;
static float vrefint_raw = 0.0f;     /* one-shot VREFINT 12-bit probe */
static uint16_t threshold_high = 3000;
static uint16_t threshold_low  = 1000;
static uint8_t alarm_active = 0;
static uint8_t blink_state = 0;

/*---------- Measure 电压曲线图 ----------*
 * 环形缓冲区保存最近 N 个 measured_voltage 采样点.
 * 屏幕图表区: x=[PLOT_X0..PLOT_X1], y=[PLOT_Y0..PLOT_Y1].
 * 横轴 = 时间 (左旧右新, 滚动), 纵轴 = 0~3.3V (满量程). */
#define PLOT_N          120   /* 120 点 × 200ms = 24 秒历史 */
#define PLOT_X0         10
#define PLOT_X1         230
#define PLOT_Y0         180   /* 图表区顶 */
#define PLOT_Y1         300   /* 图表区底 */
#define PLOT_W          (PLOT_X1 - PLOT_X0 + 1)
#define PLOT_H          (PLOT_Y1 - PLOT_Y0 + 1)
#define PLOT_VMIN       0.0f
#define PLOT_VMAX       3.3f

/* plot_idx 语义: 下一个要被新采样覆盖的位置.
 * 屏幕上"plot_idx 处"的像素当前仍是旧值, 即将被擦掉并用新值重画. */
static float plot_buf[PLOT_N];   /* 环形缓冲 */
static uint16_t plot_idx = 0;     /* 下一个写入位置 (0..PLOT_N-1) */
static uint8_t  plot_filled = 0;  /* 0=还没填满, 1=已填满开始环形滚动 */

/*---------- 延时 ----------*/
static void delay_ms_local(uint32_t ms) { delay_ms(ms); }

/*---------- GPIO 初始化 ----------*/
static void gpio_init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOCEN | RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOEEN | RCC_AHB1ENR_GPIOFEN;

    /* PD12-PD15: output (LEDs, active-low) */
    GPIOD->MODER &= ~(0xFFU << 24);
    GPIOD->MODER |=  (0x55U << 24);
    GPIOD->OTYPER &= ~(0xFU << 12);
    GPIOD->ODR &= ~LED_ALL;   /* active-low: 0=亮 */

    /* PE2, PE3, PE4: input pull-up (KEY0/KEY1/KEY2) */
    GPIOE->MODER &= ~(0x3FU << 4);
    GPIOE->PUPDR &= ~(0x3FU << 4);
    GPIOE->PUPDR |=  (0x15U << 4);

    /* PF8: output, push-pull, no pull-up, default LOW (静音). active-high.
     * 之前因为 PUPDR 未设 (浮空) 导致蜂鸣器一直叫, 现改为下拉. */
    GPIOF->MODER   &= ~(3U << 16);
    GPIOF->MODER   |=  (1U << 16);    /* output */
    GPIOF->OTYPER  &= ~(1U << 8);
    GPIOF->OSPEEDR |=  (3U << 16);
    GPIOF->PUPDR   &= ~(3U << 16);
    GPIOF->PUPDR   |=  (2U << 16);    /* pull-down, 参考 ALIENTEK beep.c */
    GPIOF->ODR     &= ~BUZZER_PIN;    /* PF8=0 默认静音 */
}

/*---------- 按键检测 (非阻塞, 下降沿) ----------*
 * 三个按键均在 GPIOE，按下拉低（上拉有效）。
 * KEY0(PE4) = 电压+0.1V
 * KEY1(PE3) = 电压-0.1V
 * KEY2(PE2) = 报警清除
 * 非阻塞：记录上一次电平，在"高→低"跳变时触发一次，不卡循环。 */
static uint8_t key0_prev = 1, key1_prev = 1, key2_prev = 1;

static uint8_t key0_pressed(void)   /* KEY0 PE4 */
{
    uint8_t cur = (GPIOE->IDR & KEY0_PIN) ? 1 : 0;
    uint8_t edge = (key0_prev == 1 && cur == 0);
    key0_prev = cur;
    return edge;
}

static uint8_t key1_pressed(void)   /* KEY1 PE3 */
{
    uint8_t cur = (GPIOE->IDR & KEY1_PIN) ? 1 : 0;
    uint8_t edge = (key1_prev == 1 && cur == 0);
    key1_prev = cur;
    return edge;
}

static uint8_t key2_pressed(void)   /* KEY2 PE2 */
{
    uint8_t cur = (GPIOE->IDR & KEY2_PIN) ? 1 : 0;
    uint8_t edge = (key2_prev == 1 && cur == 0);
    key2_prev = cur;
    return edge;
}

/*---------- LED/蜂鸣器 (active-low: 高=灭, 低=亮/响) ----------*/
static void led_on(uint32_t led)     { GPIOD->ODR &= ~led; }   /* 低电平点亮 */
static void led_off(uint32_t led)    { GPIOD->ODR |= led; }    /* 高电平熄灭 */
static void led_toggle(uint32_t led) { GPIOD->ODR ^= led; }
/* 蜂鸣器 (PF8): active-high — PF8=1 响, PF8=0 静音 */
static void buzzer_on(void)          { GPIOF->ODR |= BUZZER_PIN; }     /* PF8=1 响 */
static void buzzer_off(void)         { GPIOF->ODR &= ~BUZZER_PIN; }    /* PF8=0 静音 */

/*---------- 浮点转字符串 ----------*/
static void float_to_str(float val, char *buf, int decimals)
{
    int int_part = (int)val;
    float frac = val - (int)val;
    int i = 0;
    if (int_part == 0) {
        buf[i++] = '0';
    } else {
        char tmp[10]; int j = 0, n = int_part;
        while (n > 0) { tmp[j++] = '0' + (n % 10); n /= 10; }
        for (int k = j - 1; k >= 0; k--) buf[i++] = tmp[k];
    }
    buf[i++] = '.';
    for (int d = 0; d < decimals; d++) {
        frac *= 10.0f;
        int digit = (int)frac;
        buf[i++] = '0' + digit;
        frac -= digit;
    }
    buf[i] = '\0';
}

/*---------- 串口状态报告 ----------*/
static void send_status(void)
{
    char buf[32];
    uart_send_string("\r\n========== Status ==========\r\n");

    uart_send_string("Target:   ");
    float_to_str(target_voltage, buf, 2);
    uart_send_string(buf); uart_send_string(" V\r\n");

    uart_send_string("Measured: ");
    float_to_str(measured_voltage, buf, 2);
    uart_send_string(buf); uart_send_string(" V\r\n");

    uart_send_string("Window: [");
    uart_send_number(threshold_low);
    uart_send_string(" - ");
    uart_send_number(threshold_high);
    uart_send_string("]  Volt: [");
    float_to_str((float)threshold_low * 3.3f / 4095.0f, buf, 2);
    uart_send_string(buf); uart_send_string(" ~ ");
    float_to_str((float)threshold_high * 3.3f / 4095.0f, buf, 2);
    uart_send_string(buf); uart_send_string(" V]\r\n");

    uart_send_string("Alarm: ");
    uart_send_string(alarm_active ? "ACTIVE <<<\r\n" : "OFF\r\n");

    uart_send_string("ChipTemp: ");
    float_to_str(chip_temperature, buf, 1);
    uart_send_string(buf); uart_send_string(" C\r\n");
    uart_send_string("============================\r\n");
}

/*---------- 串口命令解析 ----------*/
static void parse_command(const char *cmd)
{
    if (cmd[0] == 'V' && cmd[1] == ':') {
        float val = 0.0f;
        const char *p = cmd + 2;
        while (*p >= '0' && *p <= '9') { val = val * 10.0f + (*p - '0'); p++; }
        if (*p == '.') { float f = 0.1f; p++; while (*p >= '0' && *p <= '9') { val += (*p - '0') * f; f *= 0.1f; p++; } }
        if (val > 3.3f) val = 3.3f;
        target_voltage = val;
        dac_set_voltage(val);
        uart_send_string("OK: V=");
        char buf[16]; float_to_str(val, buf, 2);
        uart_send_string(buf); uart_send_string(" V\r\n");

    } else if (cmd[0] == 'H' && cmd[1] == ':') {
        uint16_t val = 0;
        const char *p = cmd + 2;
        while (*p >= '0' && *p <= '9') { val = val * 10 + (*p - '0'); p++; }
        if (val > 4095) val = 4095;
        threshold_high = val;
        ADC1->HTR = val;
        uart_send_string("OK: H="); uart_send_number(val); uart_send_string("\r\n");

    } else if (cmd[0] == 'L' && cmd[1] == ':') {
        uint16_t val = 0;
        const char *p = cmd + 2;
        while (*p >= '0' && *p <= '9') { val = val * 10 + (*p - '0'); p++; }
        if (val > 4095) val = 4095;
        threshold_low = val;
        ADC1->LTR = val;
        uart_send_string("OK: L="); uart_send_number(val); uart_send_string("\r\n");

    } else if (cmd[0] == '?') {
        send_status();

    } else if (cmd[0] == 'R' || cmd[0] == 'r') {
        alarm_active = 0;
        adc_watchdog_clear();
        buzzer_off();
        uart_send_string("OK: Alarm cleared\r\n");

    } else {
        uart_send_string("Commands: V:x.xx H:nnnn L:nnnn ? R\r\n");
    }
}

/*---------- 串口接收缓冲区 ----------*/
static char rx_buf[32];
static uint8_t rx_idx = 0;

/*---------- LCD 显示 ----------*/
/* 把电压值映射到图表 y 坐标 (PLOT_Y0=上, PLOT_Y1=下, 满量程 PLOT_VMIN..VMAX) */
static inline uint16_t plot_v_to_y(float v)
{
    if (v < PLOT_VMIN) v = PLOT_VMIN;
    if (v > PLOT_VMAX) v = PLOT_VMAX;
    /* 反转: v=VMAX -> y=PLOT_Y0 (上), v=VMIN -> y=PLOT_Y1 (下) */
    float frac = (v - PLOT_VMIN) / (PLOT_VMAX - PLOT_VMIN);
    return PLOT_Y1 - (uint16_t)(frac * (float)(PLOT_H - 1));
}

/* 把环形缓冲下标 idx 映射到 x 坐标 (左旧右新, 但 idx 越大表示越新) */
static inline uint16_t plot_idx_to_x(uint16_t idx)
{
    /* idx: 0 = 最旧, PLOT_N-1 = 最新; x: PLOT_X0 = 最旧, PLOT_X1 = 最新 */
    return PLOT_X0 + (uint32_t)idx * (PLOT_W - 1) / (PLOT_N - 1);
}

/* Draw the static labels once at startup (title + field names + chart frame). */
static void lcd_draw_layout(void)
{
    POINT_COLOR = BLACK;
    BACK_COLOR  = WHITE;
    LCD_Clear(WHITE);

    /* Title bar */
    POINT_COLOR = WHITE;
    LCD_Fill(0, 0, lcddev.width - 1, 24, BLUE);
    LCD_ShowString(8, 4, lcddev.width - 8, 24, 16, (u8 *)"Closed-Loop Control System");

    POINT_COLOR = BLACK;
    LCD_ShowString(10, 32,  200, 16, 16, (u8 *)"Target  V:");
    LCD_ShowString(10, 52,  200, 16, 16, (u8 *)"Measure V:");
    LCD_ShowString(10, 72,  200, 16, 16, (u8 *)"Window   :");
    LCD_ShowString(10, 92,  200, 16, 16, (u8 *)"Chip Temp:");
    LCD_ShowString(10, 112, 200, 16, 16, (u8 *)"Alarm    :");

    /* ===== 图表区静态部分: 边框 + 网格 + 阈值线 + Y 轴标签 ===== */
    /* Chart title */
    POINT_COLOR = DARKBLUE;
    LCD_ShowString(10, 134, 200, 16, 12, (u8 *)"Measure V History:");
    POINT_COLOR = BLACK;

    /* Outer frame (rectangle) */
    LCD_DrawRectangle(PLOT_X0 - 1, PLOT_Y0 - 1, PLOT_X1 + 1, PLOT_Y1 + 1);

    /* Horizontal grid lines at 1/4, 1/2, 3/4 (light gray) */
    POINT_COLOR = GRAY;
    for (uint8_t i = 1; i <= 3; i++) {
        uint16_t y = PLOT_Y0 + i * PLOT_H / 4;
        LCD_DrawLine(PLOT_X0, y, PLOT_X1, y);
    }

    /* Y-axis labels (right-aligned outside frame) */
    POINT_COLOR = BLACK;
    LCD_ShowChar(PLOT_X1 + 4, PLOT_Y0 - 6,     '3', 12, 0);
    LCD_ShowString(PLOT_X1 + 12, PLOT_Y0 - 6,  20, 12, 12, (u8 *)".3V");
    LCD_ShowString(PLOT_X1 + 4, PLOT_Y1 - 8,   20, 12, 12, (u8 *)"0V");
    LCD_ShowString(PLOT_X1 + 4, (PLOT_Y0 + PLOT_Y1) / 2 - 6, 20, 12, 12, (u8 *)"1.6V");

    /* Threshold lines (dashed effect via dotted: short dashes) */
    POINT_COLOR = MAGENTA;
    {
        uint16_t yh = plot_v_to_y((float)threshold_high * 3.3f / 4095.0f);
        uint16_t yl = plot_v_to_y((float)threshold_low  * 3.3f / 4095.0f);
        /* dotted horizontal line: draw 4px on / 4px off */
        for (uint16_t x = PLOT_X0; x <= PLOT_X1; x += 8) {
            uint16_t xe = (x + 4 <= PLOT_X1) ? (x + 4) : PLOT_X1;
            LCD_DrawLine(x, yh, xe, yh);
            LCD_DrawLine(x, yl, xe, yl);
        }
    }
    POINT_COLOR = BLACK;
}

/* Show a float value as "d.dd" starting at (x,y). idigits = integer digits. */
static void lcd_show_float(u16 x, u16 y, float val, u8 size, u8 idigits)
{
    if (val < 0) val = 0;
    uint16_t whole = (uint16_t)val;
    uint16_t frac  = (uint16_t)((val - whole) * 100.0f + 0.5f);
    if (frac >= 100) { whole += 1; frac -= 100; }
    u16 hw = size / 2;               /* character cell width */
    LCD_ShowNum(x, y, whole, idigits, size);
    x += idigits * hw;
    LCD_ShowChar(x, y, '.', size, 0);           x += hw;
    LCD_ShowNum(x, y, frac / 10, 1, size);      x += hw;
    LCD_ShowNum(x, y, frac % 10, 1, size);
}

/* Refresh the dynamic values on the LCD. */
static void lcd_update_values(void)
{
    const u16 vx = 100;   /* value column */

    POINT_COLOR = BLUE;
    lcd_show_float(vx, 32, target_voltage, 16, 1);
    LCD_ShowString(vx + 60, 32, 40, 16, 16, (u8 *)"V");

    POINT_COLOR = alarm_active ? RED : GREEN;
    lcd_show_float(vx, 52, measured_voltage, 16, 1);
    LCD_ShowString(vx + 60, 52, 40, 16, 16, (u8 *)"V");

    /* Window thresholds (12-bit raw) */
    POINT_COLOR = BLACK;
    LCD_ShowNum(vx, 72, threshold_low, 4, 16);
    LCD_ShowChar(vx + 40, 72, '-', 16, 0);
    LCD_ShowNum(vx + 56, 72, threshold_high, 4, 16);

    /* Chip temperature (2 integer digits) */
    POINT_COLOR = MAGENTA;
    lcd_show_float(vx, 92, chip_temperature, 16, 2);
    LCD_ShowString(vx + 4 * 8, 92, 40, 16, 16, (u8 *)"C");

    /* Alarm state */
    if (alarm_active) {
        POINT_COLOR = RED;
        LCD_ShowString(vx, 112, 120, 16, 16, (u8 *)"ALARM! ");
    } else {
        POINT_COLOR = GREEN;
        LCD_ShowString(vx, 112, 120, 16, 16, (u8 *)"NORMAL ");
    }

    /* ===== 图表增量绘制 (环形 strip chart) =====
     * 不变式: 屏幕 x=plot_idx_to_x(plot_idx) 处当前画着 plot_buf[plot_idx] 的旧值.
     *
     * 每帧:
     *   (a) 白色擦掉 (prev_idx, plot_idx) 旧线段 (只有在 plot_idx 处确有
     *       旧线段可擦时才行).
     *   (b) 把新采样写入 plot_buf[plot_idx].
     *   (c) 画 (prev_idx, plot_idx) 新线段.
     *
     * plot_idx==0 特殊处理 (避免跨屏长线):
     *   - 未填满: plot_idx==0 表示该位置从未画过线段, 跳过擦与画.
     *   - 已填满: 跳过 (因为擦会跨屏; 但 plot_idx=1 时的擦 (0,1) 会
     *     经过 x=10 这一列, 顺手把 plot_idx=0 处的旧纵坐标抹掉). */
    {
        uint16_t x_cur = plot_idx_to_x(plot_idx);
        uint16_t prev_idx = (plot_idx == 0) ? (PLOT_N - 1) : (plot_idx - 1);
        int do_draw = (plot_idx > 0);   /* plot_idx=0 时永不画 (避免跨屏) */

        if (do_draw) {
            /* (a) 擦旧线段 */
            uint16_t x_prev = plot_idx_to_x(prev_idx);
            uint16_t y_prev_old = plot_v_to_y(plot_buf[prev_idx]);
            uint16_t y_cur_old  = plot_v_to_y(plot_buf[plot_idx]);
            POINT_COLOR = WHITE;
            LCD_DrawLine(x_prev, y_prev_old, x_cur, y_cur_old);
        }

        /* (b) 写入新值 */
        plot_buf[plot_idx] = measured_voltage;

        if (do_draw) {
            /* (c) 画新线段 */
            uint16_t x_prev = plot_idx_to_x(prev_idx);
            uint16_t y_prev_new = plot_v_to_y(plot_buf[prev_idx]);
            uint16_t y_cur_new  = plot_v_to_y(plot_buf[plot_idx]);
            POINT_COLOR = alarm_active ? RED : BLUE;
            LCD_DrawLine(x_prev, y_prev_new, x_cur, y_cur_new);
        }

        plot_idx = (plot_idx + 1) % PLOT_N;
        if (plot_idx == 0) plot_filled = 1;
    }

    POINT_COLOR = BLACK;
}


int main(void)
{
    system_init();
    gpio_init();
    uart_init(115200);
    dac_init();
    adc_init();
    LCD_Init();

    /* LED heartbeat: blink to confirm code is running */
    led_on(LED_BLUE);

    lcd_draw_layout();

    uart_send_string("\r\n=== Closed-Loop Control System ===\r\n");
    uart_send_string("DAC(PA4)->ADC(PA0) Window Watchdog\r\n");
    uart_send_string("Keys: PC0=UP(+0.1V) PC1=DOWN(-0.1V)\r\n");
    uart_send_string("UART: V:x.xx H:nnnn L:nnnn ? R\r\n\r\n");

    dac_set_voltage(target_voltage);
    ADC1->HTR = threshold_high;
    ADC1->LTR = threshold_low;
    adc_watchdog_enable(1);

    while (1) {
        uint32_t now = get_tick();

        /*--- LED heartbeat (500ms) ---*/
        static uint32_t last_hb_tick = 0;
        if ((now - last_hb_tick) >= 500) {
            last_hb_tick = now;
            led_toggle(LED_BLUE);
        }

        /*--- 按键扫描 (200ms) ---*
         * KEY2 (PE2) = 左键 → 电压 +0.1V
         * KEY0 (PE4) = 右键 → 电压 -0.1V
         * KEY1 (PE3) = 下键 → 报警清除
         */
        static uint32_t last_key_tick = 0;
        if ((now - last_key_tick) >= 200) {
            last_key_tick = now;
            if (key2_pressed()) {        /* PE2 左键: 电压+0.1V */
                target_voltage += 0.1f;
                if (target_voltage > 3.3f) target_voltage = 3.3f;
                dac_set_voltage(target_voltage);
                uart_send_string("KEY2+: V=");
                char buf[16]; float_to_str(target_voltage, buf, 2);
                uart_send_string(buf); uart_send_string(" V\r\n");
            }
            if (key0_pressed()) {        /* PE4 右键: 电压-0.1V */
                target_voltage -= 0.1f;
                if (target_voltage < 0.0f) target_voltage = 0.0f;
                dac_set_voltage(target_voltage);
                uart_send_string("KEY0-: V=");
                char buf[16]; float_to_str(target_voltage, buf, 2);
                uart_send_string(buf); uart_send_string(" V\r\n");
            }
            if (key1_pressed()) {        /* PE3 下键: 报警清除 */
                alarm_active = 0;
                adc_watchdog_clear();
                uart_send_string("KEY1: Alarm cleared\r\n");
            }
        }

        /*--- ADC采集 + 窗口检测 (50ms) ---*/
        static uint32_t last_adc_tick = 0;
        if ((now - last_adc_tick) >= 50) {
            last_adc_tick = now;
            uint16_t adc_raw = adc_read();
            measured_voltage = (float)adc_raw * 3.3f / 4095.0f;
            /* 超出窗口 -> 报警; 回到窗口内 -> 自动解除. */
            if (adc_raw > threshold_high || adc_raw < threshold_low) {
                alarm_active = 1;
            } else {
                alarm_active = 0;
            }
            /* 注意: 不在这里动 LED, 留给报警闪烁块控制 */
        }

        /*--- 报警: LED闪烁 + 蜂鸣器鸣叫 (250ms 周期) ---*
         * PD14/PD15 被 LCD FSMC 数据线占用, 报警闪烁用 PD12(Green) + PD13(Orange).
         * 蜂鸣器 (PF8, active-high) 同步鸣叫, 形成间断报警 (哔-哔-哔).
         * 正常状态: PD12 常亮, PD13 常灭, 蜂鸣器静音. */
        static uint32_t last_blink_tick = 0;
        if (alarm_active) {
            if ((now - last_blink_tick) >= 250) {
                last_blink_tick = now;
                blink_state ^= 1;
                if (blink_state) {
                    led_off(LED_GREEN);
                    led_on(LED_ORANGE);
                    buzzer_on();         /* 前半周期: 鸣叫 */
                } else {
                    led_on(LED_GREEN);
                    led_off(LED_ORANGE);
                    buzzer_off();        /* 后半周期: 静音 */
                }
            }
        } else {
            led_on(LED_GREEN);
            led_off(LED_ORANGE);
            buzzer_off();                /* 正常状态强制静音 */
        }

        /*--- 芯片温度采集 (500ms) ---*/
        static uint32_t last_temp_tick = 0;
        if ((now - last_temp_tick) >= 500) {
            last_temp_tick = now;
            chip_temperature = adc_read_temperature();
            /* One-shot VREFINT probe (ADC1_IN17, ~1.21V bandgap). With Vdda=3.3V,
             * expected raw ≈ 1.21/3.3 * 4095 ≈ 1502. Read via SWD. */
            static uint8_t vref_probed = 0;
            if (!vref_probed) {
                vrefint_raw = (float)adc_read_vrefint_raw();
                vref_probed = 1;
            }
        }

        /*--- LCD 刷新 (200ms) ---*/
        static uint32_t last_lcd_tick = 0;
        if ((now - last_lcd_tick) >= 200) {
            last_lcd_tick = now;
            lcd_update_values();
        }

        /*--- 串口自动上报 (2s) ---*/
        static uint32_t last_report_tick = 0;
        if ((now - last_report_tick) >= 2000) {
            last_report_tick = now;
            send_status();
        }

        /*--- 串口接收 ---*/
        int c = uart_receive_char();
        if (c >= 0) {
            if (c == '\r' || c == '\n') {
                if (rx_idx > 0) { rx_buf[rx_idx] = '\0'; parse_command(rx_buf); rx_idx = 0; }
            } else {
                if (rx_idx < sizeof(rx_buf) - 1) rx_buf[rx_idx++] = (char)c;
            }
        }
    }
}
